## Copyright © 2021, Oracle and/or its affiliates. 
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

    title: "Demo OCI Resource Manager with Oracle NoSQL Database Cloud Service - Table2"
    description: "Demo OCI Resource Manager with Oracle NoSQL Database Cloud Service"
    informationalText: "Modern apps benefit from predictable low latency, flexibility, and horizontal scale-out of NoSQL databases. Join us to learn how effortless it is to develop a modern app using Oracle Cloud Infrastructure and Oracle NoSQL Database Cloud Service. This lab is based on data from an airline baggage tracking app"
    instructions: "Please choose the region Phoenix and Choose "
    troubleshooting: "Need Help"
    stackDescription: "Learn and Discover why NoSQL Cloud Services and OCI native services are compelling"
    schemaVersion: 1.1.0
    version: "20220101"
    locale: "en"


    variableGroups:
    - title: General Configuration
      visible: false
      variables:
      - tenancy_ocid
      - region

    - title: Required Configuration
      visible: true  
      variables:
      - compartment_ocid
      - always_free       

    variables:

      compartment_ocid:
        type: oci:identity:compartment:id
        required: true
        visibile: true
        title: Compartment
        description: "Compartment where you want to create the solution resources"

      region:
        type: oci:identity:region:name
        required: true
        visibile: true
        title: Region
        description: "Region where you want to deploy the resources defined by this stack."
          
      always_free:
        type: boolean
        title: "NOSQL always free ?"
        description: "The NOSQL tables will create with the option always free"
        visible: true
        
