name: oci-terraform-build-stack
on:
  push:
    paths:
      - 'oci-resource-manager-terraform-scripts/*/*'
      - '.github/workflows/build-nosql-stack.yaml'
  workflow_dispatch:     
jobs:
  build-stack:
    name: Build Stack zip files
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Build Stack'
        run: |
          zip -r ./stack1.zip oci-resource-manager-terraform-scripts/table1/*
          zip -r ./stack2.zip oci-resource-manager-terraform-scripts/table2/*
      - name: 'Publish Stack 1'
        uses: actions/upload-artifact@v3
        with:
          name: stack1
          path: 'stack1.zip'

      - name: 'Publish Stack 2'
        uses: actions/upload-artifact@v3
        with:
          name: stack2
          path: 'stack2.zip'
          
      - name: 'Create Release'
        if: success()
        id: create_release
        uses: actions/create-release@v1
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: livelab-XXX-latest
          release_name: Release livelab-XXX-latest
          body: |
            This release is generated from the workflow build-nosql-stack.yaml
          draft: false
          prerelease: false
      
      - name: print
        run: |
          echo ${{steps.create_release.outputs.upload_url}}
        
      - name: 'Upload Release Asset (Stack 1)'
        id: upload-release-asset-stack-1
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: ./stack1.zip
          asset_name: stack1.zip
          asset_content_type: application/zip
          
      - name: 'Upload Release Asset (Stack 2)'
        id: upload-release-asset-stack-2
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: ./stack2.zip
          asset_name: stack2.zip
          asset_content_type: application/zip
          
